#!/usr/bin/env bash

if [ "$(uname)" != "Linux" ]; then
    echo "you need to be on a linux"
    exit 1
fi

# rust btw
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

# go??? i need to install this
# lua btw
cargo install stylua

# luarocks
pushd /tmp/luarocks-3.11.0
(
    wget --output-document /tmp/luarocks.tar.gz https://luarocks.org/releases/luarocks-3.11.0.tar.gz
    tar zxpf /tmp/luarocks.tar.gz -C /tmp
    cd
    ./configure && make && sudo make install
)
popd

luarocks install luacheck
